name: CI - release

on:
  push:
    branches:
      - master
jobs:
  
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 10.x
      
    - name: Enter in foler source
      run: cd src
      
    - name: Install dependencies 
      run: yarn install
    
    - name: Build app
      run: yarn build
      
    - name: Remove map files
      run: rm -rf ./build/**/*.map      
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: SystoreFront
        path: ./src/build
