name: CI - release

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Docker Registry      
      run: echo -n ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build Docker image
      run: docker build . --file docker/Dockerfile --tag ${{ secrets.DOCKER_IMAGE_REGISTRY }}/systore-frontend:latest

    - name: Create tag image
      run: docker tag ${{ secrets.DOCKER_IMAGE_REGISTRY }}/systore-frontend:latest ${{ secrets.DOCKER_IMAGE_REGISTRY }}/systore-frontend:$(date +%d-%m-%Y-%H-%M-%S)
    
    - name: Push images
      run: docker push ${{ secrets.DOCKER_IMAGE_REGISTRY }}/systore-frontend
